apiVersion: v1
kind: Service
metadata:
    name: bookstoreapi-service
spec:
    selector:
        app: bookstore-app
    ports: 
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
    type: LoadBalancer  
    

---
apiVersion: apps/v1
kind: Deployment
metadata: 
    name: bookstore-app
spec:
    selector:
        matchLabels: bookstore-app
    replicas: 3
    template:
        metadata:
            labels:
                app: bookstore-app
        spec:
            containers:
            - name: bookstore-app
              image: bookstore-app
              imagePullPolicy: ifNotPresent
              ports:
              - containerPort: 5000
